### ISSUE TITLE
Does not seem to work

### ISSUE THREAD

**Issue by Dayforbananafish** [julesmoretti/fancrawl#4]
Dear Jules,

After I successfully login with Instagram and turn on Fancrawl, nothing happens, 0 crawled.
Does it work/ do i need to be approved?

Thank you.

**Comment by julesmoretti** [comment]
Thank you for writing. It should work now. Let me know if it does not. Also you can leave here the Instagram handle you are using and I can looking deeper into it.

Also note that lately Instagram has changed the way one sign-in and error handling a too so it makes it difficult to upkeep this system.

Looking forward to hearing more about it.
